

    
    ---
    kind: Service
    apiVersion: v1
    metadata:
    name: my-springboot-app
    spec:
    selector:
    app: my-springboot
    ports:
    - protocol: "TCP"
    # Port accessible inside cluster
    port: 8080
    # Port to forward to inside the pod
    targetPort: 8080
    # Port accessible outside cluster
    #angularPort: 30567
    type: LoadBalancer

    ---
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
    name: my-springboot-app-deploy
    spec:
    replicas: 1
    template:
    metadata:
    labels:
    app: my-springboot
    spec:
    containers:
    - name: my-springboot-app-container
    image: jeevakiran/backend-kubernetes
    ports:
    - containerPort: 8080

